### ISSUE TITLE
What are the python versions that we wiill support? Lets define it.

### ISSUE THREAD

**Issue by infinite-Joy** [turingnetworkai/turingnetwork#14]

**Comment by hhsecond** [comment]
@infinite-Joy fixed with #15 
Let me know what you think

**Comment by infinite-Joy** [comment]
Awesome. lets keep this issue open for now as we need infrastructure to ensure that this is the case. This includes:

* documentation (I guess this is done.)
* writing the supporting tox files.

In case you have knowledge on other supporting infrastructure that we may need to enforce this, lets keep all the tasks here.

**Comment by hhsecond** [comment]
@infinite-Joy 
Documentation will be improved as we go, for sure.
Since the current package (this repo) only supports python 3.5+, I guess we are good with env checks also. I haven't used tox yet, but we are [testing with python3.5 and python3.6](https://travis-ci.org/dlguys/flashlight) already in travis. I'll add python3.7 once it is out in June
For users who need older version support, we'll write separate FlashLight client which will be another repo
